dist: trusty
git:
  depth: 1
language: node_js
sudo: required


before_install:
  - ./docker-util/sh/install-docker-on-trusty.sh
  - sudo service docker stop
  - sudo dockerd --experimental &
  - docker version

env:
  global:
    - DOCKER_IMAGE_NAME=travis-cli
    - DOCKER_PROD_IMAGE_NAME=beeglercorp/$DOCKER_IMAGE_NAME
    - DOCKER_STAGE_IMAGE_NAME=beeglercorpstage/$DOCKER_IMAGE_NAME
    - IMAGE_SIZE_THRESHOLD=35

install: true

stages:
  - name: Build
    if: type = pull_request
  - name: Stage Image
    if: branch = stage AND type = push
  - name: Compare Build to Stage
    if: branch = master AND type = push AND env(COMPARE_BUILD_TO_STAGE) IS present
  - name: Promote Stage to Prod
    if: branch = master AND type = push

jobs:
  include:

    - stage: Build
      env:
        - ALPINE_VERSION=latest
        - TAG=latest
      script:
        - ./sh/ci/build.sh

    - stage: Build
      env:
        - ALPINE_VERSION=edge
        - TAG=alpine-$ALPINE_VERSION
      script:
        - ./sh/ci/build.sh

    - stage: Build
      env:
        - ALPINE_VERSION=3.5
        - TAG=alpine-$ALPINE_VERSION
      script:
        - ./sh/ci/build.sh

    - stage: Stage Image
      env:
        - ALPINE_VERSION=latest
        - DOCKER_PUBLIC_IMAGE_NAME=$DOCKER_STAGE_IMAGE_NAME
        - TAG=latest
      script:
        - ./sh/ci/build.sh
        - ./sh/ci/push.sh
        - ./sh/ci/test-pull.sh

    - stage: Stage Image
      env:
        - ALPINE_VERSION=edge
        - DOCKER_PUBLIC_IMAGE_NAME=$DOCKER_STAGE_IMAGE_NAME
        - TAG=alpine-$ALPINE_VERSION
      script:
        - ./sh/ci/build.sh
        - ./sh/ci/push.sh
        - ./sh/ci/test-pull.sh

    - stage: Stage Image
      env:
        - ALPINE_VERSION=3.5
        - DOCKER_PUBLIC_IMAGE_NAME=$DOCKER_STAGE_IMAGE_NAME
        - TAG=alpine-$ALPINE_VERSION
      script:
        - ./sh/ci/build.sh
        - ./sh/ci/push.sh
        - ./sh/ci/test-pull.sh

    - stage: Compare Build to Stage
      env:
        - ALPINE_VERSION=latest
        - TAG=latest
      script:
        - ./sh/ci/build.sh
        - docker pull $DOCKER_STAGE_IMAGE_NAME
        - ./docker-util/sh/compare-images.sh $DOCKER_IMAGE_NAME $DOCKER_STAGE_IMAGE_NAME

    - stage: Compare Build to Stage
      env:
        - ALPINE_VERSION=edge
        - TAG=alpine-$ALPINE_VERSION
      script:
        - ./sh/ci/build.sh
        - docker pull $DOCKER_STAGE_IMAGE_NAME
        - ./docker-util/sh/compare-images.sh $DOCKER_IMAGE_NAME $DOCKER_STAGE_IMAGE_NAME

    - stage: Compare Build to Stage
      env:
        - ALPINE_VERSION=3.5
        - TAG=alpine-$ALPINE_VERSION
      script:
        - ./sh/ci/build.sh
        - docker pull $DOCKER_STAGE_IMAGE_NAME
        - ./docker-util/sh/compare-images.sh $DOCKER_IMAGE_NAME $DOCKER_STAGE_IMAGE_NAME

    - stage: Promote Stage to Prod
      env:
        - ALPINE_VERSION=latest
        - TAG=latest
        - DOCKER_IMAGE_NAME=$DOCKER_STAGE_IMAGE_NAME:$TAG
        - DOCKER_PUBLIC_IMAGE_NAME=$DOCKER_PROD_IMAGE_NAME
      script:
        - docker pull $DOCKER_IMAGE_NAME
        - ./sh/ci/push.sh
        - ./sh/ci/test-pull.sh

    - stage: Promote Stage to Prod
      env:
        - ALPINE_VERSION=edge
        - TAG=alpine-$ALPINE_VERSION
        - DOCKER_IMAGE_NAME=$DOCKER_STAGE_IMAGE_NAME:$TAG
        - DOCKER_PUBLIC_IMAGE_NAME=$DOCKER_PROD_IMAGE_NAME
      script:
        - docker pull $DOCKER_IMAGE_NAME
        - ./sh/ci/push.sh
        - ./sh/ci/test-pull.sh

    - stage: Promote Stage to Prod
      env:
        - ALPINE_VERSION=3.5
        - TAG=alpine-$ALPINE_VERSION
        - DOCKER_IMAGE_NAME=$DOCKER_STAGE_IMAGE_NAME:$TAG
        - DOCKER_PUBLIC_IMAGE_NAME=$DOCKER_PROD_IMAGE_NAME
      script:
        - docker pull $DOCKER_IMAGE_NAME
        - ./sh/ci/push.sh
        - ./sh/ci/test-pull.sh
